name: classroom_tracker
description: A Classroom Tracker app for students that tracks classroom availability.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  provider: ^6.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  http: ^1.2.1
  icalendar_parser: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_foreground_inset: 16

flutter:
  uses-material-design: true
