// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PO1deRNVrF9bFStkZ2yQ8ej4kF2tgyk',
    appId: '1:35081935560:web:33214fb6140ce5097be3fd',
    messagingSenderId: '35081935560',
    projectId: 'classroomtracker-esiee',
    authDomain: 'classroomtracker-esiee.firebaseapp.com',
    storageBucket: 'classroomtracker-esiee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9RybQgqF4Gkv9WS2jGRa6w6LipD-V5Ck',
    appId: '1:35081935560:android:979b2ca90772f2e47be3fd',
    messagingSenderId: '35081935560',
    projectId: 'classroomtracker-esiee',
    storageBucket: 'classroomtracker-esiee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5EYQMfcnX2mloxFa-dZdh2sLshAn7VE',
    appId: '1:35081935560:ios:fb357ab20f9d5f2e7be3fd',
    messagingSenderId: '35081935560',
    projectId: 'classroomtracker-esiee',
    storageBucket: 'classroomtracker-esiee.firebasestorage.app',
    iosBundleId: 'com.example.classroomTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ5EYQMfcnX2mloxFa-dZdh2sLshAn7VE',
    appId: '1:35081935560:ios:fb357ab20f9d5f2e7be3fd',
    messagingSenderId: '35081935560',
    projectId: 'classroomtracker-esiee',
    storageBucket: 'classroomtracker-esiee.firebasestorage.app',
    iosBundleId: 'com.example.classroomTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4PO1deRNVrF9bFStkZ2yQ8ej4kF2tgyk',
    appId: '1:35081935560:web:b9b27f24326566aa7be3fd',
    messagingSenderId: '35081935560',
    projectId: 'classroomtracker-esiee',
    authDomain: 'classroomtracker-esiee.firebaseapp.com',
    storageBucket: 'classroomtracker-esiee.firebasestorage.app',
  );

}